#!/bin/bash

echo "WARNING....Are you shure? Becouse its can kill your memory!...."
sleep 3
echo "YES"
sleep 2
echo "I am so sory....By-by"
j=5

for ((i=1;i<=5;i++));
do
      echo $j
      j=$[$j-1]
      sleep 1
done

